#!/usr/bin/env bash
# Install the local toolchain for Phase 11+ as user binaries (no sudo), under
# ~/.local/opt/<tool>-<version> with entry points in ~/.local/bin.
#
#   scripts/prereqs/install.sh              # install everything missing
#   scripts/prereqs/install.sh node pg age  # only some tools
#   scripts/prereqs/install.sh --link-az    # make the Linux Azure CLI the default `az`
#
# Every download is pinned and verified with SHA-256 (npm packages are verified by
# npm's own registry integrity check). Downloads use IPv4 only: IPv6 from WSL2 to
# some registries hangs. Idempotent: an installed version is left alone.
# Check the result with scripts/prereqs/check.sh.
set -euo pipefail

OPT="$HOME/.local/opt"
BIN="$HOME/.local/bin"
mkdir -p "$OPT" "$BIN"

NODE_VERSION="22.23.3"
NODE_SHA256="df450af89261115ef9f9e3830c3eeb2cc9213b63c720b1af623cb5dcbe2e02de"
NPM_VERSION="11.20.0"

# PostgreSQL 16 client from the PGDG archive (Ubuntu 26.04 "resolute" build) and the
# libpq it needs; unpacked with dpkg-deb, never installed system-wide.
PGDG="https://apt.postgresql.org/pub/repos/apt/pool/main/p"
PG_CLIENT_DEB="postgresql-client-16_16.15-1.pgdg26.04+2_amd64.deb"
PG_CLIENT_SHA256="52fd38615ce65bd9b0442a21e611986e0cc7b87e1143e2464668be17fcb77314"
LIBPQ_DEB="libpq5_18.6-1.pgdg26.04+2_amd64.deb"
LIBPQ_SHA256="a56bfe4843ae432e7338d0139190397db69a343412e489ae637bfb39c2d6fc30"
PG_DIR="$OPT/pg-client-16.15"

AGE_VERSION="1.3.2"
AGE_SHA256="cbe24006683f8eb669266162894b9a522a1af52f2665fbc63a4bb032ed26ac10"

SHELLCHECK_VERSION="0.11.0"
SHELLCHECK_SHA256="8c3be12b05d5c177a04c29e3c78ce89ac86f1595681cab149b65b97c4e227198"

GH_VERSION="2.101.0"
GH_SHA256="9bca2d1c16825f109907a23307628a2f0698fbf99662b73a5cf0b020293072b8"

AZ_VERSION="2.90.0"
AZ_PYTHON="3.12"
AZ_DIR="$OPT/azure-cli-$AZ_VERSION"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

log() { echo "[install] $*"; }

# fetch <url> <sha256> <output>
fetch() {
  curl -4 -fsSL --retry 3 -o "$3" "$1"
  echo "$2  $3" | sha256sum -c --quiet -
}

install_node() {
  local dir="$OPT/node-v$NODE_VERSION"
  if [ ! -x "$dir/bin/node" ]; then
    local tarball="node-v$NODE_VERSION-linux-x64.tar.xz"
    log "node $NODE_VERSION"
    fetch "https://nodejs.org/dist/v$NODE_VERSION/$tarball" "$NODE_SHA256" "$TMP/$tarball"
    mkdir -p "$dir"
    tar -xJf "$TMP/$tarball" -C "$dir" --strip-components=1
  fi
  # npm's shebang resolves `node` through PATH, and npm derives its global prefix
  # from that node: put this install first so npm 11 lands in "$dir".
  if [ "$(PATH="$dir/bin:$PATH" npm --version)" != "$NPM_VERSION" ]; then
    log "npm $NPM_VERSION"
    PATH="$dir/bin:$PATH" NODE_OPTIONS="--dns-result-order=ipv4first" \
      npm install -g --no-fund --no-audit "npm@$NPM_VERSION"
  fi
  # Replace any older user-level node/npm entry points (a previous install left a
  # plain `node` binary and npm symlinks into ~/.local/lib/node_modules).
  local tool
  for tool in node npm npx corepack; do
    ln -sfn "$dir/bin/$tool" "$BIN/$tool"
  done
}

install_pg() {
  if [ ! -x "$PG_DIR/usr/lib/postgresql/16/bin/pg_dump" ]; then
    log "PostgreSQL 16 client (PGDG)"
    fetch "$PGDG/postgresql-16/$PG_CLIENT_DEB" "$PG_CLIENT_SHA256" "$TMP/client.deb"
    fetch "$PGDG/postgresql-18/$LIBPQ_DEB" "$LIBPQ_SHA256" "$TMP/libpq.deb"
    mkdir -p "$PG_DIR"
    dpkg-deb -x "$TMP/client.deb" "$PG_DIR"
    dpkg-deb -x "$TMP/libpq.deb" "$PG_DIR"
  fi
  local tool
  for tool in psql pg_dump pg_restore pg_dumpall pg_isready; do
    cat > "$BIN/$tool" <<EOF
#!/usr/bin/env bash
# Generated by scripts/prereqs/install.sh: PostgreSQL 16 client (user install).
export LD_LIBRARY_PATH="$PG_DIR/usr/lib/x86_64-linux-gnu\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
exec "$PG_DIR/usr/lib/postgresql/16/bin/$tool" "\$@"
EOF
    chmod +x "$BIN/$tool"
  done
}

install_age() {
  local dir="$OPT/age-v$AGE_VERSION"
  if [ ! -x "$dir/age" ]; then
    local tarball="age-v$AGE_VERSION-linux-amd64.tar.gz"
    log "age $AGE_VERSION"
    fetch "https://github.com/FiloSottile/age/releases/download/v$AGE_VERSION/$tarball" \
      "$AGE_SHA256" "$TMP/$tarball"
    mkdir -p "$dir"
    tar -xzf "$TMP/$tarball" -C "$dir" --strip-components=1
  fi
  ln -sfn "$dir/age" "$BIN/age"
  ln -sfn "$dir/age-keygen" "$BIN/age-keygen"
}

install_shellcheck() {
  local dir="$OPT/shellcheck-v$SHELLCHECK_VERSION"
  if [ ! -x "$dir/shellcheck" ]; then
    local tarball="shellcheck-v$SHELLCHECK_VERSION.linux.x86_64.tar.xz"
    log "shellcheck $SHELLCHECK_VERSION"
    fetch "https://github.com/koalaman/shellcheck/releases/download/v$SHELLCHECK_VERSION/$tarball" \
      "$SHELLCHECK_SHA256" "$TMP/$tarball"
    mkdir -p "$dir"
    tar -xJf "$TMP/$tarball" -C "$dir" --strip-components=1
  fi
  ln -sfn "$dir/shellcheck" "$BIN/shellcheck"
}

install_gh() {
  local dir="$OPT/gh-$GH_VERSION"
  if [ ! -x "$dir/bin/gh" ]; then
    local tarball="gh_${GH_VERSION}_linux_amd64.tar.gz"
    log "gh $GH_VERSION"
    fetch "https://github.com/cli/cli/releases/download/v$GH_VERSION/$tarball" \
      "$GH_SHA256" "$TMP/$tarball"
    mkdir -p "$dir"
    tar -xzf "$TMP/$tarball" -C "$dir" --strip-components=1
  fi
  ln -sfn "$dir/bin/gh" "$BIN/gh"
}

# Linux Azure CLI in its own venv (uv-managed Python). Exposed as `az-linux` so it
# does not shadow the Windows `az` (already logged in) until the user has run
# `az-linux login`; then `install.sh --link-az` makes it the default `az` in WSL.
install_az() {
  if [ ! -x "$AZ_DIR/bin/az" ]; then
    command -v uv >/dev/null || { echo "uv is required for the Azure CLI venv" >&2; return 1; }
    log "azure-cli $AZ_VERSION (venv, Python $AZ_PYTHON)"
    uv venv -q --python "$AZ_PYTHON" "$AZ_DIR"
    uv pip install -q --python "$AZ_DIR/bin/python" "azure-cli==$AZ_VERSION"
  fi
  ln -sfn "$AZ_DIR/bin/az" "$BIN/az-linux"
}

link_az() {
  [ -x "$AZ_DIR/bin/az" ] || { echo "install the Linux Azure CLI first" >&2; return 1; }
  ln -sfn "$AZ_DIR/bin/az" "$BIN/az"
  log "\`az\` in WSL now runs the Linux Azure CLI ($AZ_VERSION)"
}

main() {
  if [ "${1:-}" = "--link-az" ]; then
    link_az
    return
  fi
  local tools=("$@")
  [ ${#tools[@]} -eq 0 ] && tools=(node pg age shellcheck gh az)
  local t
  for t in "${tools[@]}"; do
    case "$t" in
      node) install_node ;;
      pg) install_pg ;;
      age) install_age ;;
      shellcheck) install_shellcheck ;;
      gh) install_gh ;;
      az) install_az ;;
      *) echo "unknown tool: $t (node pg age shellcheck gh az)" >&2; exit 2 ;;
    esac
  done
  log "done — run scripts/prereqs/check.sh"
}

main "$@"
