"use client";

import { useEffect, useRef, useState } from "react";

/* ============================================================================
   VaultDoor — ASCII-art vault door, ported from the vault_ascii.html prototype.

   The geometry (crearPuerta / sampleVault) and the in-browser font measurement
   (medirCelda) are preserved verbatim: the door is generated by formula, and the
   cell aspect ratio is measured live so the circle stays round with any monospace
   font. The open-sequence state machine (idle -> girando -> abriendo -> dentro)
   is unchanged; only the rendering host moved from vanilla DOM to a React ref.

   mode="interactive": shows the ABRIR button and runs the full open sequence,
     calling onOpened() when it reaches "dentro".
   mode="static": draws the resting door once (landing hero) — no spin, no button.

   Respects prefers-reduced-motion: the open sequence is skipped and onOpened()
   fires immediately, so the login form is always reachable without motion.
   ========================================================================== */

const T = { LINEA: 0.99, MEDIO: 0.66, HUECO: 0.42, CHAPA: 0.14 };

function clasePorTono(v: number): string {
  if (v >= 0.9) return "c-linea";
  if (v >= 0.55) return "c-medio";
  if (v >= 0.3) return "c-hueco";
  return "c-chapa";
}

interface DoorConfig {
  R: number;
  nPernos: number;
  nRadios: number;
  rLlanta: number;
  junta: number;
}

type SampleFn = (x: number, y: number, giro: number, retraccion: number) => number | null;

function crearPuerta(cfg: DoorConfig): SampleFn {
  const R = cfg.R,
    NP = cfg.nPernos,
    NR = cfg.nRadios;
  const rHub = R * 0.17,
    rLlanta = R * cfg.rLlanta,
    junta = cfg.junta;

  function manecilla(x: number, y: number, giro: number, retraccion: number): number | null {
    const r = Math.hypot(x, y),
      th = Math.atan2(y, x);
    const paso = (2 * Math.PI) / NR;
    const k = Math.round((th - giro) / paso);
    const ang = giro + k * paso;
    const knob = 1.5 * (1 - retraccion * 0.35);

    const kx = Math.cos(ang) * (rLlanta + knob * 0.55),
      ky = Math.sin(ang) * (rLlanta + knob * 0.55);
    const dk = Math.hypot(x - kx, y - ky);
    if (dk < knob) return dk > knob - 0.6 ? T.LINEA : T.MEDIO;

    if (r > rLlanta + 0.7) return null;
    if (Math.abs(r - rLlanta) < 0.7) return T.LINEA;
    if (r <= rHub) return rHub - r < 0.7 ? T.LINEA : T.HUECO;
    const dth = ((th - ang + Math.PI) % (2 * Math.PI)) - Math.PI;
    if (Math.abs(r * dth) < 1.15) return Math.abs(r * dth) > 0.3 ? T.LINEA : T.MEDIO;
    return null;
  }

  return function sample(x: number, y: number, giro: number, retraccion: number): number | null {
    const r = Math.hypot(x, y),
      th = Math.atan2(y, x);

    const v = manecilla(x, y, giro, retraccion);
    if (v !== null) return v;

    if (r <= R) {
      if (R - r < 0.75) return T.LINEA;
      if (Math.abs(r - R * junta) < 0.42) return T.LINEA;
      const paso = (2 * Math.PI) / NP;
      const k = Math.round(th / paso);
      const bolt = 1.0 * (1 - retraccion);
      const px = Math.cos(k * paso) * R * 0.845,
        py = Math.sin(k * paso) * R * 0.845;
      const dp = Math.hypot(x - px, y - py);
      if (bolt > 0.02 && dp < bolt) return dp > bolt * 0.55 ? T.LINEA : T.HUECO;
      return T.CHAPA;
    }
    const L = R + 3.2;
    if (Math.max(Math.abs(x), Math.abs(y)) <= L) {
      if (Math.max(Math.abs(x), Math.abs(y)) > L - 0.8 || r < R + 1.1) return T.LINEA;
      return T.MEDIO;
    }
    return null;
  };
}

const sampleVault = crearPuerta({ R: 13.5, nPernos: 12, nRadios: 4, rLlanta: 0.52, junta: 0.68 });

// Real font measurement: derive the cell aspect ratio from the box a character
// actually occupies in this browser, instead of assuming one.
function medirCelda(pre: HTMLElement): { cw: number; ch: number } {
  const sonda = document.createElement("span");
  sonda.textContent = "MMMMMMMMMM";
  sonda.style.visibility = "hidden";
  pre.appendChild(sonda);
  const rect = sonda.getBoundingClientRect();
  pre.removeChild(sonda);
  return { cw: rect.width / 10, ch: rect.height };
}

const COLS = 62;
const FILAS = 32;

interface VaultDoorProps {
  mode: "interactive" | "static";
  onOpened?: () => void;
}

export default function VaultDoor({ mode, onOpened }: VaultDoorProps) {
  const preRef = useRef<HTMLPreElement>(null);
  const envoltorioRef = useRef<HTMLDivElement>(null);
  const startRef = useRef<() => void>(() => {});
  const [hint, setHint] = useState("turn the wheel to unlock");
  const [btnDisabled, setBtnDisabled] = useState(false);

  useEffect(() => {
    const pre = preRef.current;
    const envoltorio = envoltorioRef.current;
    if (!pre) return;

    let aspecto = 0.5;

    function remedir() {
      const { cw, ch } = medirCelda(pre!);
      if (cw > 0 && ch > 0) aspecto = cw / ch;
    }

    function dibuja(giro: number, retraccion: number, zoom: number) {
      const filas: string[] = [];
      for (let row = 0; row < FILAS; row++) {
        let fila = "",
          claseActual: string | null = null,
          tramo = "";
        const cerrar = () => {
          if (tramo) fila += claseActual ? `<span class="${claseActual}">${tramo}</span>` : tramo;
          tramo = "";
        };
        for (let col = 0; col < COLS; col++) {
          const x = ((col - COLS / 2 + 0.5) * aspecto) / zoom;
          const y = (FILAS / 2 - row - 0.5) / zoom;
          const v = sampleVault(x, y, giro, retraccion);
          const chr = v === null ? " " : "░▒▓█"[Math.min(3, Math.floor(v * 4))];
          const clase = v === null ? null : clasePorTono(v);
          if (clase !== claseActual) {
            cerrar();
            claseActual = clase;
          }
          tramo += chr;
        }
        cerrar();
        filas.push(fila);
      }
      pre!.innerHTML = filas.join("\n");
    }

    remedir();

    // ---- Static mode: draw the resting door once and redraw on resize. ----
    if (mode === "static") {
      dibuja(0, 0, 1);
      const onResize = () => {
        remedir();
        dibuja(0, 0, 1);
      };
      window.addEventListener("resize", onResize);
      return () => window.removeEventListener("resize", onResize);
    }

    // ---- Interactive mode: the open-sequence state machine. ----
    const reducedMotion =
      typeof window !== "undefined" &&
      window.matchMedia("(prefers-reduced-motion: reduce)").matches;

    let estado: "idle" | "girando" | "abriendo" | "dentro" = "idle";
    let t0 = 0,
      giroBase = 0.0,
      ultimoTS = 0;
    const DURACION_GIRO = 1.1,
      DURACION_ZOOM = 1.0;
    const facil = (t: number) => t * t * (3 - 2 * t); // smoothstep

    // idle "clic": rest, then a clean 2*PI/nRadios (90°) turn, then rest again.
    const PASO_TRINQUETE = (2 * Math.PI) / 4;
    const REPOSO_MS = 2200,
      TIRON_MS = 650;
    let faseIdle: "reposo" | "tiron" = "reposo",
      faseT0 = 0,
      anguloDesde = 0,
      anguloHasta = 0;

    let rafId = 0;

    function frame(ts: number) {
      const dt = Math.min(0.05, (ts - (ultimoTS || ts)) / 1000);
      ultimoTS = ts;

      if (estado === "idle") {
        if (faseT0 === 0) faseT0 = ts;
        if (faseIdle === "reposo") {
          dibuja(giroBase, 0, 1);
          if (ts - faseT0 > REPOSO_MS) {
            faseIdle = "tiron";
            faseT0 = ts;
            anguloDesde = giroBase;
            anguloHasta = giroBase + PASO_TRINQUETE;
          }
        } else {
          const t = Math.min(1, (ts - faseT0) / TIRON_MS);
          giroBase = anguloDesde + (anguloHasta - anguloDesde) * facil(t);
          dibuja(giroBase, 0, 1);
          if (t >= 1) {
            giroBase = anguloHasta % (2 * Math.PI);
            faseIdle = "reposo";
            faseT0 = ts;
          }
        }
      } else if (estado === "girando") {
        const t = Math.min(1, (ts - t0) / (DURACION_GIRO * 1000));
        const velocidad = 0.35 + facil(t) * 14;
        giroBase += dt * velocidad;
        dibuja(giroBase, facil(t), 1);
        if (t >= 1) {
          estado = "abriendo";
          t0 = ts;
          setHint("entering…");
        }
      } else if (estado === "abriendo") {
        const t = Math.min(1, (ts - t0) / (DURACION_ZOOM * 1000));
        giroBase += dt * 6;
        const zoom = 1 + facil(t) * 22;
        dibuja(giroBase, 1, zoom);
        if (envoltorio) envoltorio.style.opacity = String(1 - facil(t) * 0.9);
        if (t >= 1) {
          estado = "dentro";
          onOpened?.();
          return; // stop the loop; the door is "open"
        }
      }
      rafId = requestAnimationFrame(frame);
    }

    startRef.current = () => {
      if (estado !== "idle") return;
      if (reducedMotion) {
        // No motion: snap to the open state and reveal the form immediately.
        estado = "dentro";
        dibuja(giroBase, 1, 1);
        setHint("entering…");
        setBtnDisabled(true);
        onOpened?.();
        return;
      }
      estado = "girando";
      t0 = performance.now();
      setHint("unlocking…");
      setBtnDisabled(true);
    };

    const onResize = () => remedir();
    window.addEventListener("resize", onResize);
    rafId = requestAnimationFrame(frame);

    return () => {
      cancelAnimationFrame(rafId);
      window.removeEventListener("resize", onResize);
    };
  }, [mode, onOpened]);

  return (
    <div className="flex w-full flex-col items-center gap-5 px-4 py-6">
      <div ref={envoltorioRef} className="leading-[0] will-change-transform">
        <pre
          ref={preRef}
          aria-hidden="true"
          className="m-0 select-none whitespace-pre text-vault-steel"
          style={{ fontSize: "clamp(6px, 1.9vw, 12px)", lineHeight: 1.02, letterSpacing: 0 }}
        />
      </div>

      {mode === "interactive" && (
        <>
          <button
            type="button"
            onClick={() => startRef.current()}
            disabled={btnDisabled}
            className="cursor-pointer border border-vault-steel-dark bg-transparent px-6 py-2.5 text-xs tracking-[0.22em] text-vault-amber transition-colors hover:border-vault-amber hover:text-vault-amber-bright focus-visible:border-vault-amber focus-visible:outline-none disabled:cursor-default disabled:opacity-35"
          >
            ABRIR
          </button>
          <div className="text-[11px] tracking-[0.1em] text-vault-steel-dark">{hint}</div>
        </>
      )}
    </div>
  );
}
